# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            码客小栈
tagline:          技术随笔
description:      "技术笔记。NodeJS,Java."
url:              https://lfnhxt.github.io/
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           zhangxw
  url:            https://lfnhxt.github.io/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/lfnhxt/lfnhxt.github.io
